name: Pull Request Code test

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  checks:
    name: run
    runs-on: [ self-hosted, dpdk ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Download metalbond using the script
        run: ./hack/rel_download.sh -dir=build -owner=ironcore-dev -repo=metalbond -pat=${{ secrets.GITHUB_TOKEN }}

      - name: Install metalbond
        run: sudo dpkg -i build/metalbond*.deb

      - name: Start metalbond
        run: metalbond server --listen [::1]:4711 --http [::1]:4712 --keepalive 3 &

      - name: Run dp-service
        run: docker run --rm --entrypoint ./dp_service.py --privileged -p1337:1337 --mount type=bind,source=/dev/hugepages,target=/dev/hugepages ghcr.io/ironcore-dev/dpservice-tester:main --no-init &

      - name: Run wait for tcp port
        run: timeout 10 bash -c 'until echo > /dev/tcp/localhost/1337 2>/dev/null; do sleep 1; done' 2>/dev/null

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: make test
      - name: Delete git global config
        if: always()
        run: |
          rm -f ~/.gitconfig
      - name: Cleanup services
        if: always()
        run: |
          killall metalbond
          for i in $(docker ps -q); do docker stop $i; done
